### ISSUE TITLE
Tracking remaining `2022.12` test suite coverage

### ISSUE THREAD

**Issue by honno** [data-apis/array-api-tests#193]
The test suite has excellent coverage of the first `2021.12` spec release, but hasn't been updated to cover all the `2022.12` additions and changes. The following is a list of things that ideally the test suite would do:

- [x] https://github.com/data-apis/array-api-tests/issues/187
  - Ideally we'd have a stubs package to use instead, i.e. https://github.com/data-apis/array-api/pull/472
  - [ ] Then we can support testing new special cases
- [x] Test the [`fft` extension](https://data-apis.org/array-api/2022.12/extensions/fourier_transform_functions.html)
  - We definitely want to at least test the dtype and broadcasting behaviour of these functions—and by virtue, smoke test them with valid inputs. Values testing is non-trivial enough to probably not be worth doing.

**Comment by honno** [comment]
Ofc @asmeurer and folks feel free to edit the original post, this is just what immediately came to mind.

**Comment by asmeurer** [comment]
The submodule thing also prevents the signature tests for working with any signature updates post 2022.12

We'll need to check with how the scipy stuff is going, but it's likely we'll want to prioritize fft testing, so that we can implement it numpy.array_api (https://github.com/numpy/numpy/issues/23892) and the compat library.

**Comment by asmeurer** [comment]
I think whatever's still missing here should be covered by other open issues in this repo.
